imports:
    - { resource: security.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    serializer:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../app/cache/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

sensio_framework_extra:
    view:
        annotations: false

monolog:
    handlers:
        syslog:
            type:                stream
            path:                /var/log/symfony.log
            level:               ERROR
            bubble:              false
        main:
            type:                fingers_crossed
            action_level:        WARNING
            buffer_size:         100
            handler:             syslog
